"""pyresponse - A simple web framework in Python that respects pure OOP."""

__version__ = "0.2.0"

from pyresponse import fork, lifespan, request, response
from pyresponse.asgi import AsgiApp
from pyresponse.error import Error
from pyresponse.fork import (
    Adapted,
    Delete,
    Endpoint,
    Fallback,
    Fixed,
    Fork,
    Get,
    Method,
    Options,
    Patch,
    Post,
    Prefix,
    Put,
    Regex,
    RouteNotFound,
    Trap,
)
from pyresponse.lifespan import Fake as Fake, Lifespan
from pyresponse.request import (
    Asgi,
    AuthNotFound,
    BasicAuth,
    BearerToken,
    Cookie,
    CookieNotFound,
    Cookies,
    Envelope as Envelope,
    FieldNotFound,
    Files,
    Form,
    Head as RequestHead,
    Header,
    HeaderNotFound,
    Multipart,
    ParamNotFound,
    Path as RequestPath,
    PathParam,
    PathParams,
    QueryParam,
    QueryParams,
    Request,
    RequestForm,
    Sticky,
    UploadFile,
    UploadNotFound,
    UrlEncoded,
)
from pyresponse.response import (
    BadRequest,
    Binary,
    Body,
    Created,
    Json,
    NoContent,
    NotFound,
    Ok,
    Redirect,
    Response,
    ServerError,
    Sse,
    StatusLine,
    Text,
    WithBody,
    WithCookie,
    WithoutCookie,
)
from pyresponse.server import Server

__all__ = [
    "__version__",
    # Submodules
    "fork",
    "request",
    "response",
    "lifespan",
    # Core Interfaces & App
    "AsgiApp",
    "Server",
    "Error",
    "Request",
    "Response",
    "Endpoint",
    "Fork",
    "Fallback",
    "Lifespan",
    "Fake",
    "Adapted",
    # Request Objects
    "Asgi",
    "Sticky",
    "Envelope",
    "RequestHead",
    "Header",
    "RequestPath",
    "PathParam",
    "PathParams",
    "QueryParam",
    "QueryParams",
    "Cookie",
    "Cookies",
    "BearerToken",
    "BasicAuth",
    "Form",
    "Files",
    "RequestForm",
    "Multipart",
    "UploadFile",
    "UrlEncoded",
    # Routing Forks
    "Get",
    "Post",
    "Put",
    "Patch",
    "Delete",
    "Options",
    "Prefix",
    "Method",
    "Regex",
    "Trap",
    # Responses & Status Lines
    "Ok",
    "Created",
    "NoContent",
    "BadRequest",
    "NotFound",
    "ServerError",
    "StatusLine",
    "Json",
    "Text",
    "Binary",
    "Body",
    "WithBody",
    "Sse",
    "Redirect",
    "WithCookie",
    "WithoutCookie",
    # Domain Exceptions
    "HeaderNotFound",
    "ParamNotFound",
    "FieldNotFound",
    "UploadNotFound",
    "CookieNotFound",
    "AuthNotFound",
    "RouteNotFound",
]
